name: call_companion
description: "Revolutionize sales team productivity with an intelligent call management app that records, transcribes, and summarizes customer conversations in real-time, powered by AI for instant insights and strategic guidance."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  firebase_core: '>=2.21.1'
  firebase_auth: '>=5.3.3'
  cloud_firestore: '>=5.5.0'
  firebase_storage: ^13.0.0
  provider: ^6.0.0
  record: '>=5.1.2'
  audioplayers: ^6.0.0
  http: ^1.0.0
  shared_preferences: ^2.0.0
  permission_handler: ^12.0.0
  uuid: ^4.0.0
  intl: 0.20.2
  path_provider: ^2.0.0
  flutter_dotenv: ^5.1.0
  flutter_background_service: ^5.0.5
  flutter_background_service_android: ^6.2.2
  # Bumped to avoid Android ambiguous method overload error with newer SDKs
  flutter_local_notifications: ^17.0.0
  phone_state: ^1.0.3
  call_log: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/dreamflow_icon.jpg
  remove_alpha_ios: true
